### ISSUE TITLE
Script error on registration form

### ISSUE THREAD

**Issue by pippinsplugins** [danieliser/rcp-taxamo#3]
I getting script errors on the registration form: 
![screen shot 2014-12-30 at 3 26 15 pm](https://cloud.githubusercontent.com/assets/1034109/5583044/5309e5dc-9038-11e4-87ff-3a4fb3f07c86.png)

**Comment by danieliser** [comment]
Did you get this resolved on your test site?

**Comment by pippinsplugins** [comment]
Testing again now.

**Comment by pippinsplugins** [comment]
Fixed!
