### ISSUE TITLE
Placement of VAT Fields

### ISSUE THREAD

**Issue by danieliser** [danieliser/rcp-taxamo#4]
So in order to get proper placement I had to add a hook here https://github.com/danieliser/Restrict-Content-Pro/blob/master/templates/register.php#L53

The only other places to put hook it either meant it only showed up if they weren't logged in, or came before the registration/login fields which seemed out of place, third was below the pricing which didn't make since as the price options update dynamically when you change to a country with tax.

**Comment by pippinsplugins** [comment]
PR merged.
