### ISSUE TITLE
Fatal error: failed opening

### ISSUE THREAD

**Issue by pippinsplugins** [danieliser/rcp-taxamo#5]
I'm getting this when clicking `Register`:
```
Fatal error: require(): Failed opening required '/Users/pippin/Sites/edd/wp-content/plugins/rcp-taxamo//includes/libraries/taxamo-php/lib/Taxamo.php' (include_path='.:/Applications/MAMP/bin/php/php5.6.2/lib/php') in /Users/pippin/Sites/edd/wp-content/plugins/rcp-taxamo/includes/class-rcp-taxamo-payments.php on line 193
```

**Comment by danieliser** [comment]
Hey Pippin, the git uses a submodule, make sure you are cloning/pulling recurrsively or just pull the submodules.

The version on wp.org has it bundled as files.

**Comment by danieliser** [comment]
Check the includes/library/taxamo-php folder if its empty simply clone https://github.com/taxamo/taxamo-php into it.

**Comment by pippinsplugins** [comment]
Hmm, unable to get it to pull. `git pull origin master -r`?

**Comment by danieliser** [comment]
try `git pull origin master --recurse-submodules`

**Comment by pippinsplugins** [comment]
No, still fails.

**Comment by danieliser** [comment]
The git pull fails or the error still exists?

Can you verify that file exists?  That error is too basic to really be an issue. Just not sure why the file isn't in there already.

Im gonna remove the git submodule and simply place the files there and recommit. Try grabbing it again in a few minutes.

**Comment by pippinsplugins** [comment]
Git says everything is up to date even with recursive. taxamo lib folder is
empty.

**Comment by danieliser** [comment]
I think I found it and will add submodule back in a bit. For testing use the one I just pushed.

There were apparently 2 instances of the submodule in the .git/config file. This caused bugs like not pulling properly and inability to remove submodule without manual editing.

**Comment by pippinsplugins** [comment]
Ah, that would do it. I'll be on the road in 5 minutes so won't be able to
test again today. Sorry.

**Comment by danieliser** [comment]
No worries, will fire up a test server and run a from scratch test using the setup guide i wrote into readme. Will at least prove users are able to get up and running.

Were the Stripe JS changes confirmed to work? Didn't see that PR get merged, and users will need that update to use with RCP-Stripe.

**Comment by danieliser** [comment]
Although I have outlined how they can currently make the change themselves. But haven't released that.
